services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  # Bind only to localhost
    restart: always
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local